[project]
name = "slay-the-princess"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.11.20",
    "networkx>=3.4.2",
    "parsimonious>=0.10.0",
    "polars>=1.25.2",
    "sqlite-utils>=3.38",
]

